name: Deploy to Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buil:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: git config user.name "fred532" && git config user.email "mail@mail.com"
      - run: npm run deploy
